services:
  stm32-dfu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stm32-dfu
    working_dir: /work
    volumes:
      - ./:/work
    devices:
      - /dev/bus/usb:/dev/bus/usb
    device_cgroup_rules:
      - "c 189:* rmw"
    stdin_open: true
    tty: true
